In [2]:
import numpy as np

In [4]:
a=np.array([[[78,55,32,32],[85,86,2,1],[4,5,6,2],[88,96,45,4]]])

In [6]:
a

array([[[78, 55, 32, 32],
        [85, 86,  2,  1],
        [ 4,  5,  6,  2],
        [88, 96, 45,  4]]])

In [8]:
a.size

16

In [11]:
a.ndim

3

In [13]:
a.data

In [15]:
z=np.zeros((5,7))

In [17]:
z

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [24]:
q=np.full((3,5),5)
q

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

In [26]:
w=np.zeros((5,3,7))
w

array([[[0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.]]])

In [33]:
r=np.random.rand(3,5)
r

array([[0.27180155, 0.40033698, 0.79585485, 0.90346334, 0.65977708],
       [0.75252572, 0.94174138, 0.80601278, 0.97979859, 0.37363946],
       [0.92204257, 0.92997543, 0.51782053, 0.09276858, 0.47819447]])

In [36]:
r=np.ones((2,3))
r

array([[1., 1., 1.],
       [1., 1., 1.]])

In [40]:
r=np.eye(4)
r

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [43]:
a.size

16

In [44]:
a.shape

(1, 4, 4)

In [46]:
a.dtype

dtype('int64')

In [59]:
v=a.reshape(4,4,1)
v

array([[[ 1],
        [ 2],
        [ 5],
        [ 6]],

       [[ 2],
        [ 4],
        [55],
        [78]],

       [[ 4],
        [32],
        [85],
        [86]],

       [[32],
        [45],
        [88],
        [96]]])

In [50]:
a

array([[[78, 55, 32, 32],
        [85, 86,  2,  1],
        [ 4,  5,  6,  2],
        [88, 96, 45,  4]]])

In [53]:
a.sort()
a

array([[[32, 32, 55, 78],
        [ 1,  2, 85, 86],
        [ 2,  4,  5,  6],
        [ 4, 45, 88, 96]]])

In [57]:
a.sort(axis=0)
a

array([[[ 1,  2,  5,  6],
        [ 2,  4, 55, 78],
        [ 4, 32, 85, 86],
        [32, 45, 88, 96]]])

In [58]:
a.sort(axis=1)
a

array([[[ 1,  2,  5,  6],
        [ 2,  4, 55, 78],
        [ 4, 32, 85, 86],
        [32, 45, 88, 96]]])

In [66]:
m=np.array([[5,6,7],[7,9,5],[1,2,5]])
m

array([[5, 6, 7],
       [7, 9, 5],
       [1, 2, 5]])

In [67]:
m.shape


(3, 3)